# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumables', models.CharField(max_length=1000)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Cena zamówienia')),
                ('delivery_address', models.CharField(max_length=100, verbose_name='Adres dostarczenia')),
                ('phone_number', models.IntegerField(verbose_name='Numer telefonu')),
                ('accepted', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
